apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    exercise: "04"
type: Opaque
stringData:
  DB_HOST: "postgres.default.svc.cluster.local"
  DB_USER: "admin"
  DB_PASSWORD: "exercise-password-123"
